version: "3.8"

services:
  cups:
    build: .
    image: drcoccodrillus/cups-filters:dev
    container_name: cups-filters
    restart: always
    privileged: true
    networks:
      printer-network:
        ipv4_address: 172.28.0.3

networks:
  printer-network:
    name: printer-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
